### ISSUE TITLE
Errors while trying to run through vignette("Joost_et_al") demo

### ISSUE THREAD

**Issue by Caryn-Willis** [mkarikom/RSoptSC#10]
I've been trying to run through the demo and have been running into some bugs. First, for the logdata <- log10(data + 1), should be logdata <- log10(GSE67602_Joost$data + 1).

I'm also having trouble with the inputs for GetMarkerTable. 

> markers <- GetMarkerTable(counts_data = filtered_data,
+                           cluster_labels = labels,
+                           H = H,
+                           n_sorted = 25,
+                           gene_names = gene_names,
+                           gene_expression_threshold = 3,
+                           n_features = 20000,
+                           use_H = TRUE)

gives:
Error in GetMarkerTable(counts_data = filtered_data, cluster_labels = labels,  : 
  unused arguments (gene_names = gene_names, n_features = 20000)

> markers <- GetMarkerTable(counts_data = filtered_data,
+                           cluster_labels = labels,
+                           H = H,
+                           n_sorted = 25,
+                           gene_expression_threshold = 3,
+                           use_H = TRUE)

gives:
Error in matrix(rownames(counts_data), ncol = 1) : 
  'data' must be of a vector type, was 'NULL'

and 
> markers <- GetMarkerTable(counts_data = filtered_data$M_variable,
+                           cluster_labels = labels,
+                           H = H,
+                           n_sorted = 25,
+                           gene_expression_threshold = 3,
+                           use_H = TRUE)

gives: Error in cbind(genes, gene_assignments) : 
  number of rows of matrices must match (see arg 2)

So, I'm not quite sure if this is an input error or a bug. 

Thanks.

**Comment by mkarikom** [comment]
Looks like chunk options on line 39 of RSoptSC.Rmd were hiding that code in the html, so line 40-43 of the vignette were not being displayed.  Should be fixed now.
