### ISSUE TITLE
Error while trying to graph cell-cell signaling circos plot

### ISSUE THREAD

**Issue by Remy-Vu** [mkarikom/RSoptSC#11]
I've been trying to plot cell-cell communication circos plot with my Seurat object. The steps up to computing the matrix work fine, but I'm having trouble with SigPlot for cell-cell signaling (cluster-cluster signaling graph works just fine)

> labels <- WO_4_1@meta.data$res.0.6
> SigPlot(P = Pmats$P_agg,
+         cluster_labels = labels,
+         lig_cells_per_cluster = 5,
+         rec_cells_per_cluster = 5,
+         rgb_gap = 0.06,
+         title_text = "Signaling Between Cells")

Error in n + 1 : non-numeric argument to binary operator

**Comment by mkarikom** [comment]
I am 99% sure this is a circlize issue but I can't check it without your P_agg matrix.  But there are changes coming that will make this a mute point:  I am replacing circos plots with igraph-based visualization, which is a much more stable, scale-able, and user-friendly platform.  Circos plots look cool but they don't really make sense unless you have a graph with 1) very few edges AND 2) a ton of attributes that have rich hierarchical structure.  Notice that in single-cell sequencing we have the exact opposite scenario...
