### ISSUE TITLE
How to install package NMF 0.23.0

### ISSUE THREAD

**Issue by zh-Bian** [mkarikom/RSoptSC#12]
the PSoptSC needs the NMF>0.23.0, however the version of the NMF is only 0.22.0. Could you please tell me how to install the PSoptSC?
Thank you.

**Comment by mkarikom** [comment]
Hi, there is a conflict in the current NMF master branch which is resolved in the dev branch

To install the required version, please run:
> devtools::install_github("renozao/NMF", ref = "devel")
