### ISSUE TITLE
Does this interface with Seurat?

### ISSUE THREAD

**Issue by ChonkyPotato** [mkarikom/RSoptSC#13]
Just curious if there is a way to integrate UMAP and cluster analysis obtained from Seurat for pseudotime analysis using this package

**Comment by mkarikom** [comment]
This should work fine, but please note that we do not support direct integration with Seurat, currently.  You would need to extract the count matrices and follow a slightly modified version of the [vignette](https://mkarikom.github.io/RSoptSC/articles/RSoptSC.html).  Please refer to the [documentation for the correct structure of cell cluster information](https://mkarikom.github.io/RSoptSC/reference/ClusterCells.html), these are just generic lists, arrays, etc but would need to be created by hand

**Comment by mkarikom** [comment]
Actually, I'm not sure it this would work, in order for the pseudotime to correspond to Seurat's clustering, the actual graph representation, or at least the similarity matrix would need to be exported from the Seurat object, not sure if that is possible on their end
