### ISSUE TITLE
Error code on installing RSoptSC

### ISSUE THREAD

**Issue by palakpatel09** [mkarikom/RSoptSC#14]
I am getting the following error upon installing RSoptSC.

 installing *source* package 'RSoptSC' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: object 'isSpike<-' is not exported by 'namespace:SingleCellExperiment'
Execution halted
ERROR: lazy loading failed for package 'RSoptSC'

Can someone please help me resolve this issue? Thank you. I have tried reinstalling SingleCellExperiment including different versions. No luck.

**Comment by mkarikom** [comment]
fixed in most recent commit
