### ISSUE TITLE
BiocNeighbor dependecy error

### ISSUE THREAD

**Issue by alevigi** [mkarikom/RSoptSC#15]
Hello, I'm trying to install RSoptsc on the cluster and I'm having problems with the BipocNeighbor dependency. 
I copied and pasted the whole error message below. 
I also tried to install the package separately in different ways but nothing works. I did not have this problem when I installed RSoptsc locally.

Any advice?

Thank you very much in advance.

In file included from annoy.cpp:1:0:
annoy.h:33:63: error: wrong number of template arguments (4, should be 5)
     typedef AnnoyIndex<Index_t, Data_t, Distance, Kiss64Random> _index;
                                                               ^
In file included from annoy.h:17:0,
                 from annoy.cpp:1:
/users/k1642876/R/x86_64-pc-linux-gnu-library/3.6/RcppAnnoy/include/annoylib.h:845:9: note: provided for ‘template<class S, class T, class Distance, class Random, class ThreadedBuildPolicy> class AnnoyIndex’
   class AnnoyIndex : public AnnoyIndexInterface<S, T> {
         ^~~~~~~~~~
annoy.cpp: In constructor ‘Annoy<Distance>::Annoy(int, const string&, double)’:
annoy.cpp:7:9: error: request for member ‘load’ in ‘((Annoy<Distance>*)this)->Annoy<Distance>::obj’, which is of non-class type ‘Annoy<Distance>::_index {aka int}’
     obj.load(fname.c_str());
         ^~~~
annoy.cpp: In member function ‘MatDim_t Annoy<Distance>::get_nobs() const’:
annoy.cpp:16:16: error: request for member ‘get_n_items’ in ‘((const Annoy<Distance>*)this)->Annoy<Distance>::obj’, which is of non-class type ‘const _index {aka const int}’
     return obj.get_n_items();
                ^~~~~~~~~~~
annoy.cpp: In member function ‘void Annoy<Distance>::find_nearest_neighbors(CellIndex_t, NumNeighbors_t, bool, bool)’:
annoy.cpp:44:9: error: request for member ‘get_nns_by_item’ in ‘((Annoy<Distance>*)this)->Annoy<Distance>::obj’, which is of non-class type ‘Annoy<Distance>::_index {aka int}’
     obj.get_nns_by_item(c, K + 1, get_search_k(K + 1), &kept_idx, dptr); // +1, as it forgets to discard 'self'.
         ^~~~~~~~~~~~~~~
annoy.cpp: In member function ‘void Annoy<Distance>::find_nearest_neighbors(const double*, NumNeighbors_t, bool, bool)’:
annoy.cpp:86:9: error: request for member ‘get_nns_by_vector’ in ‘((Annoy<Distance>*)this)->Annoy<Distance>::obj’, which is of non-class type ‘Annoy<Distance>::_index {aka int}’
     obj.get_nns_by_vector(holding.data(), K, get_search_k(K), &kept_idx, dptr);
         ^~~~~~~~~~~~~~~~~
In file included from annoy.cpp:97:0:
build_annoy.cpp: In instantiation of ‘Rcpp::RObject build_annoy_internal(Rcpp::NumericMatrix, int, const string&) [with Distance = Manhattan; Rcpp::RObject = Rcpp::RObject_Impl<Rcpp::PreserveStorage>; Rcpp::NumericMatrix = Rcpp::Matrix<14>; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
build_annoy.cpp:26:66:   required from here
build_annoy.cpp:14:13: error: request for member ‘add_item’ in ‘obj’, which is of non-class type ‘Annoy<Manhattan>::_index {aka int}’
         obj.add_item(i, tmp.data());
         ~~~~^~~~~~~~
build_annoy.cpp:17:9: error: request for member ‘build’ in ‘obj’, which is of non-class type ‘Annoy<Manhattan>::_index {aka int}’
     obj.build(Ntrees);
     ~~~~^~~~~
build_annoy.cpp:18:9: error: request for member ‘save’ in ‘obj’, which is of non-class type ‘Annoy<Manhattan>::_index {aka int}’
     obj.save(Fname.c_str());
     ~~~~^~~~
build_annoy.cpp: In instantiation of ‘Rcpp::RObject build_annoy_internal(Rcpp::NumericMatrix, int, const string&) [with Distance = Euclidean; Rcpp::RObject = Rcpp::RObject_Impl<Rcpp::PreserveStorage>; Rcpp::NumericMatrix = Rcpp::Matrix<14>; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
build_annoy.cpp:28:66:   required from here
build_annoy.cpp:14:13: error: request for member ‘add_item’ in ‘obj’, which is of non-class type ‘Annoy<Euclidean>::_index {aka int}’
         obj.add_item(i, tmp.data());
         ~~~~^~~~~~~~
build_annoy.cpp:17:9: error: request for member ‘build’ in ‘obj’, which is of non-class type ‘Annoy<Euclidean>::_index {aka int}’
     obj.build(Ntrees);
     ~~~~^~~~~
build_annoy.cpp:18:9: error: request for member ‘save’ in ‘obj’, which is of non-class type ‘Annoy<Euclidean>::_index {aka int}’
     obj.save(Fname.c_str());
     ~~~~^~~~
make: *** [annoy.o] Error 1
ERROR: compilation failed for package ‘BiocNeighbors’
* removing ‘/users/k1642876/R/x86_64-pc-linux-gnu-library/3.6/BiocNeighbors’
Error: Failed to install 'RSoptSC' from GitHub:
  (converted from warning) installation of package ‘BiocNeighbors’ had non-zero exit status

**Comment by mkarikom** [comment]
looks like you figured it out but sometimes hpc accounts require you to edit the path via so-called module loading to enable compilation of c-based dependencies

**Comment by alevigi** [comment]
Thank you so much for your reply!! yes I managed to finally install it using the remote library.

I am now struggling with running the SimilarityM function on my whole dataset (filtered_data@x     : num [1:10878000])
I managed to run it on a subset on my laptop (it took ages) now I'm on the cluster and still I can't get it to work with the whole dataset. Hours before the first Err message. Any suggestions? Thank you so much. I love this package and I already got amazing results using the subset...can't wait to see the results on the full dataset

**Comment by mkarikom** [comment]
hmm, it looks like filtered_data contains >10 million cells, is that correct?

**Comment by alevigi** [comment]
Hi..yes, I'm trying with the full dataset and a subset of it (see str of objects below) and I finally made the subset one to work. But it is taking a full day. Is that normal? now I'm calculating the clusters and it has been running for hours. 

Any suggestion on how to make things faster?

Thanks in advance. 
> str(filtered_data)
List of 2
 $ gene_use  : int [1:1000] 6 8 25 96 153 279 286 287 305 341 ...
 $ M_variable:Formal class 'dgeMatrix' [package "Matrix"] with 4 slots
  .. ..@ x       : num [1:10878000] 0 0 0.188 0.188 0.277 ...
  .. ..@ Dim     : int [1:2] 1000 10878
  .. ..@ Dimnames:List of 2
  .. .. ..$ : chr [1:1000] "Sox17" "Mrpl15" "Rrs1" "Mcm3" ...
  .. .. ..$ : chr [1:10878] "AAACCCAAGTCATGAA-1" "AAACCCACAAGATCCT-1" "AAACCCACAGTGGGTA-1" "AAACCCACATTGAGGG-1" ...
  .. ..@ factors : list()


> str(filtered_data2)
List of 2
 $ gene_use  : int [1:3000] 6 8 17 25 32 38 39 40 42 46 ...
 $ M_variable:Formal class 'dgeMatrix' [package "Matrix"] with 4 slots
  .. ..@ x       : num [1:18675000] 0 0 0 0.188 0.188 ...
  .. ..@ Dim     : int [1:2] 3000 6225
  .. ..@ Dimnames:List of 2
  .. .. ..$ : chr [1:3000] "Sox17" "Mrpl15" "Rb1cc1" "Rrs1" ...
  .. .. ..$ : chr [1:6225] "AAACCCAAGTCATGAA-1" "AAACCCACAAGATCCT-1" "AAACCCACAGTGGGTA-1" "AAACCCACATTGAGGG-1" ...
  .. ..@ factors : list()

**Comment by mkarikom** [comment]
the short answer is: yeah that kind of run time is definitely possible, and crashes can actually occur due to resource limitations, even on hpc.  for similarity matrix construction the number of cells  (`dim(filtered_data$M_variable)[2]`) is going to be the bottleneck.

the long answer is:

to be honest, the main goal of soptsc was to see how well a certain class of linear subspace methods with very good theoretical guarantees would do on cell lineage problems.  just 5 years ago, hundreds of cells (eg the Joost data we look at in the vignette) was the norm.  now its tens of thousands of cells and method performance (in terms of run times), parallelization, etc has started to become the starting point for many groups who work on these packages, including ours.  

while it's certainly possible to write blazing fast packages in R, what that entails is actually writing stuff in C, calling that from R, and making sure that R and C play well together on everything from hpc clusters to laptops.  this is known as the "two language problem".  so for me personally, it was just easier to move to a comparatively new language called julia, which natively gives speed comparable to C/Fortran in many cases, is much smarter about using optimized implementations for it's few dependencies (eg OpenBLAS), and has native support for distributed computation on hpc.

I know that's not the answer you were looking for but hopefully gives some justification for why we don't offer more support for soptsc regarding performance or hpc environments.
