### ISSUE TITLE
Installing BiocNeighbors

### ISSUE THREAD

**Issue by Samantha-Czn** [mkarikom/RSoptSC#16]
Hi @mkarikom  and @alevigi,

I have the same problem as in https://github.com/mkarikom/RSoptSC/issues/15#issuecomment-737775827_ with the "wrong number of template arguments" etc. when trying to install BiocNeighbor.

I was wondering if you could explain what you meant about editing the path and/or how to use the remote library for this?

(From the thread:
> "looks like you figured it out but sometimes hpc accounts require you to edit the path via so-called module loading to enable compilation of c-based dependencies"
> "I managed to finally install it using the remote library."

)

**Comment by jhu99** [comment]
Hi Samantha-Czn,

I have the same problem. I am wondering if you find a solution?

**Comment by Samantha-Czn** [comment]
Hi,

I can't really remember if I solved this - I was having issues with installing a bunch of packages and in the end I updated my BiocManager to version 3.12 and reinstalled everything on R 4.0.3 and none of them had any issues installing after that.

I do remember that one of the things I tried before updating was just using `install.packages("https://www.bioconductor.org/packages/release/bioc/src/contrib/BiocNeighbors_1.8.2.tar.gz", type = "source")` instead of `BiocManager::install("BiocNeighbors")` . This worked with a couple of packages for some reason, and though I can't remember if BiocNeighbors was one of them,  it might be worth trying.

Let me know if you figure it out :)

**Comment by mkarikom** [comment]
these issues were related to a bioconductor package dependency that apparently is no longer maintained (unfortunately this is not uncommon).

these should be removed now so please try reinstalling via:
```
library("devtools")
devtools::install_github("mkarikom/RSoptSC")
```
